apiVersion: v1
items:
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: "2021-09-19T02:12:23Z"
    labels:
      app: nodejs-hello
      app.kubernetes.io/component: nodejs-hello
      app.kubernetes.io/instance: nodejs-hello
      app.kubernetes.io/name: nodejs
    managedFields:
    - apiVersion: build.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:openshift.io/generated-by: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/component: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/name: {}
        f:spec:
          f:output:
            f:to:
              .: {}
              f:kind: {}
              f:name: {}
          f:runPolicy: {}
          f:source:
            f:contextDir: {}
            f:git:
              .: {}
              f:ref: {}
              f:uri: {}
            f:type: {}
          f:strategy:
            f:sourceStrategy:
              .: {}
              f:env: {}
              f:from:
                .: {}
                f:kind: {}
                f:name: {}
                f:namespace: {}
            f:type: {}
      manager: oc
      operation: Update
      time: "2021-09-19T02:12:23Z"
    - apiVersion: build.openshift.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:spec:
          f:triggers: {}
        f:status:
          f:lastVersion: {}
      manager: openshift-apiserver
      operation: Update
      time: "2021-09-19T02:12:23Z"
    name: nodejs-hello
    namespace: lxwrie-nodejs
    resourceVersion: "13821106"
    selfLink: /apis/build.openshift.io/v1/namespaces/lxwrie-nodejs/buildconfigs/nodejs-hello
    uid: 9138d039-9452-4d44-b321-2639f2cf86e6
  spec:
    failedBuildsHistoryLimit: 5
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-hello:latest
    postCommit: {}
    resources: {}
    runPolicy: Serial
    source:
      contextDir: nodejs-helloworld
      git:
        ref: troubleshoot-s2i
        uri: https://github.com/masihtech/DO180-apps
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: npm_config_registry
          value: http://nexus-common.apps.na46.prod.nextcle.com/repository/npm-proxy
        from:
          kind: ImageStreamTag
          name: nodejs:12
          namespace: openshift
      type: Source
    successfulBuildsHistoryLimit: 5
    triggers:
    - github:
        secret: hCM2fpnc2Mhqt8FfSyjn
      type: GitHub
    - generic:
        secret: 9grhpHIXU9FQiVcAALS8
      type: Generic
    - type: ConfigChange
    - imageChange:
        lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:593f8df68f12bc64f80567bb67c38a1dd06dd628722dc7aad2f29adefd9ae34e
      type: ImageChange
  status:
    lastVersion: 1
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
